# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "22.x"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Abfrage von der Repo-Variable
        run: echo "Die Repo-Variable ist $NAME"

      # Runs a single command using the runners shell
      - name: Variablen
        run: echo "${{ toJson(github) }}"

      - name: Art vom Start der Workflow
        run: echo "Die Workflow wurde durch ${{ github.event_name }} gestartet"

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Tree Befehl
        run: tree

      - name: Installieren von cowsay
        run: sudo apt-get install -y cowsay

      - name: Überprüfung von Node Version
        run: node --version 

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Platzhalter für die Umgebungsvariable
        run: echo "Die Node-Version ist $NODE_VERSION"

      - name: Überprüfung von Node Version
        run: node --version 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  couscous:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Platzhalter für die Umgebungsvariable
        run: echo "Die Node-Version ist $NODE_VERSION"